# Generated by Django 5.1.6 on 2025-02-15 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("login", models.CharField(max_length=300)),
                ("age", models.IntegerField()),
                ("location", models.CharField(max_length=300)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("ALL", "All"),
                        ],
                        max_length=300,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
