# Generated by Django 5.1.6 on 2025-02-15 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisers", "0003_campaign_cost_per_click_and_more"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "advertiser",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisers.advertiser",
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
