# Generated by Django 5.1.6 on 2025-02-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_mlscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="age",
            field=models.IntegerField(verbose_name="Возраст"),
        ),
        migrations.AlterField(
            model_name="client",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("ALL", "All")],
                max_length=300,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="location",
            field=models.CharField(max_length=300, verbose_name="Местоположение"),
        ),
        migrations.AlterField(
            model_name="client",
            name="login",
            field=models.CharField(max_length=300, verbose_name="Логин"),
        ),
        migrations.AlterField(
            model_name="mlscore",
            name="score",
            field=models.IntegerField(verbose_name="Оценка ML"),
        ),
    ]
