# Generated by Django 5.1.6 on 2025-02-19 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisers", "0005_alter_campaign_targeting"),
        ("clients", "0004_alter_mlscore_advertiser_alter_mlscore_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlscore",
            name="advertiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisers.advertiser",
                verbose_name="Рекламодатель",
            ),
        ),
        migrations.AlterField(
            model_name="mlscore",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.CreateModel(
            name="AdClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisers.campaign",
                        verbose_name="Реклама",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisers.campaign",
                        verbose_name="Реклама",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
