# Generated by Django 5.1.6 on 2025-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_alter_mlscore_advertiser_alter_mlscore_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adclick",
            name="created_at",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adimpression",
            name="created_at",
            field=models.IntegerField(default=0),
        ),
    ]
