# Generated by Django 5.1.6 on 2025-02-20 00:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_adclick_created_at_adimpression_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="adclick",
            name="cost",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adimpression",
            name="cost",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adclick",
            name="created_at",
            field=models.IntegerField(default=core.models.CurrentDate.get_today),
        ),
        migrations.AlterField(
            model_name="adimpression",
            name="created_at",
            field=models.IntegerField(default=core.models.CurrentDate.get_today),
        ),
    ]
