# Generated by Django 5.1.6 on 2025-02-13 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("ALL", "All"),
                        ],
                        max_length=350,
                        null=True,
                        verbose_name="Пол аудитории",
                    ),
                ),
                (
                    "age_from",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Мин. возраст аудитории"
                    ),
                ),
                (
                    "age_to",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Макс. возраст аудитории"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        null=True,
                        verbose_name="Локация аудитории",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="advertiser",
            name="name",
            field=models.CharField(max_length=350),
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "impressions_limit",
                    models.IntegerField(verbose_name="Лимит показов"),
                ),
                ("clicks_limit", models.IntegerField(verbose_name="Лимит переходов")),
                (
                    "cost_per_impression",
                    models.FloatField(verbose_name="Стоимость клика"),
                ),
                ("ad_title", models.CharField(max_length=350, verbose_name="Название")),
                ("ad_text", models.TextField(verbose_name="Текст объявления")),
                ("start_date", models.IntegerField(verbose_name="День начала показа")),
                ("end_date", models.IntegerField(verbose_name="Ден окончания показа")),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="advertisers.advertiser",
                        verbose_name="Рекламодатель",
                    ),
                ),
                (
                    "targeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign",
                        to="advertisers.target",
                        verbose_name="Настройки таргетинга",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
