# Generated by Django 5.1.6 on 2025-02-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisers", "0003_campaign_cost_per_click_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="click_count",
            field=models.IntegerField(default=0, verbose_name="Количество кликов"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="impression_count",
            field=models.IntegerField(default=0, verbose_name="Количество показов"),
        ),
    ]
