# Generated by Django 5.1.6 on 2025-02-16 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisers", "0004_campaign_click_count_campaign_impression_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="targeting",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign",
                to="advertisers.target",
                verbose_name="Настройки таргетинга",
            ),
        ),
    ]
