# Generated by Django 5.1.6 on 2025-02-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertisers", "0005_alter_campaign_targeting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="click_count",
            new_name="clicks_count",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="impression_count",
            new_name="impressions_count",
        ),
    ]
