# Generated by Django 5.1.6 on 2025-02-19 15:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisers", "0006_rename_click_count_campaign_clicks_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.ImageField(
                    upload_to="campaign_images", verbose_name="Изображения"
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
