# Generated by Django 5.1.6 on 2025-02-20 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisers", "0007_campaign_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="images",
        ),
        migrations.CreateModel(
            name="CampaignImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="campaign_images/", verbose_name="Изображения"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="advertisers.campaign",
                        verbose_name="Объявление",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
